# https://taskfile.dev

version: '3'

vars:
  VERSION: '0.8.1-SNAPSHOT'
  GIT_ROOT: '$HOME/git'
  REPOS:
    - util-external
    - util-internal
    - language-cst
    - language-java
    - language-inspection
    - analyzer-modification
    - analyzer-aapi
    - analyzer-run
    - analyzer-runmvn
    - e2immu-devops

  PROJECTS:
    - util-external/e2immu-external-support
    - util-internal/e2immu-internal-graph
    - util-internal/e2immu-internal-util
    - language-cst/e2immu-cst-analysis
    - language-cst/e2immu-cst-api
    - language-cst/e2immu-cst-impl
    - language-cst/e2immu-cst-io
    - language-cst/e2immu-cst-print
    - language-java/e2immu-java-bytecode
    - language-java/e2immu-java-parser
    - language-inspection/e2immu-inspection-api
    - language-inspection/e2immu-inspection-parser
    - language-inspection/e2immu-inspection-resource
    - language-inspection/e2immu-inspection-integration
    - analyzer-modification/e2immu-modification-common
    - analyzer-modification/e2immu-modification-io    
    - analyzer-modification/e2immu-modification-prepwork
    - analyzer-modification/e2immu-modification-linkedvariables
    - analyzer-aapi/e2immu-aapi-archive
    - analyzer-aapi/e2immu-aapi-parser
    - analyzer-run/e2immu-run-config
    - analyzer-run/e2immu-run-decompile
    - analyzer-run/e2immu-run-main
    - analyzer-run/e2immu-run-gradleplugin
    - analyzer-run/testgradlepluginanalyzer
    - analyzer-run/testgradlepluginwriteaapi
    - analyzer-run/testgradlepluginshallow

tasks:

  copyProperties: 
    sources:
     - gradle.properties
     - Taskfile.yml
    cmds:
      - for: { var: PROJECTS }
        cmd: cp gradle.properties {{joinPath .GIT_ROOT .ITEM}}

  publish:*:
    vars:
      REPO: '{{index .MATCH 0}}'
    dir: '{{.GIT_ROOT}}'
    label: 'repo-{{.REPO}}'
    sources: 
      - "{{.REPO}}/*/src/main/**"
    cmds:
      - cmd: cd {{.REPO}} && gradle publish -Pversion={{.VERSION}}

  publish-locally:*:
    vars:
      REPO: '{{index .MATCH 0}}'
    dir: '{{.GIT_ROOT}}'
    label: 'local-repo-{{.REPO}}'
    sources: 
      - "{{.REPO}}/*/src/main/**"
    cmds:
      - cmd: cd {{.REPO}} && gradle publishToMavenLocal -Pversion={{.VERSION}}

  publish-gradle-plugin:
    dir: '{{.GIT_ROOT}}'
    cmds:
      - cmd: cd analyzer-run && gradle :e2immu-run-gradleplugin:publish -Pversion={{.VERSION}}

  publish-maven-plugin:
    dir: '{{.GIT_ROOT}}'
    cmds:
      - cmd: cd analyzer-runmvn && mvn install -U

  # note: the analyzer-run publish action will not publish the Gradle plugin
  publish-jars:
    deps:
      - publish:util-internal
      - publish:util-external
      - publish:language-cst
      - publish:language-inspection
      - publish:language-java
      - publish:analyzer-aapi
      - publish:analyzer-modification
      - publish:analyzer-run

  publish-jars-locally:
    deps:
      - publish-locally:util-internal
      - publish-locally:util-external
      - publish-locally:language-cst
      - publish-locally:language-inspection
      - publish-locally:language-java
      - publish-locally:analyzer-aapi
      - publish-locally:analyzer-modification
      - publish-locally:analyzer-run

  git-status:
    dir: '{{.GIT_ROOT}}'
    cmds:
      - for: { var: REPOS }
        cmd: echo {{.ITEM }} ; cd {{.ITEM}} ; git branch --show-current ; git status --porcelain ; git status -sb | grep -E '^\#\# .*(\[.*\])' | grep -oE '\[(ahead|behind|diverged|gone).*\]' || true
